name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/src/**'

  deploy_hosting:
    name: Deploy Hosting
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_FOR_HOSTING }}
          create_credentials_file: true

      - name: Build
        run: npm run build

      - name: Deploy to Hosting
        run: firebase deploy --only hosting